id: PYSEC-0000-ansible-GHSA-8ggh-xwr9-3373
modified: '2026-07-07T16:03:12.042202Z'
published: '2026-07-07T16:03:12.042202Z'
aliases:
- CVE-2025-14010
- GHSA-8ggh-xwr9-3373
summary: Ansible Community General Collection is vulnerable to exposure of sensitive information
details: A flaw was found in ansible-collection-community-general. This vulnerability allows for information exposure (IE) of sensitive credentials, specifically plaintext passwords, via verbose output when running Ansible with debug modes. Attackers with access to logs could retrieve these secrets and potentially compromise Keycloak accounts or administrative access.
severity:
- type: CVSS_V3
  score: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N
affected:
- package:
    ecosystem: PyPI
    name: ansible
    purl: pkg:pypi/ansible
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: '0'
    - fixed: 12.2.0
references:
- type: ADVISORY
  url: https://nvd.nist.gov/vuln/detail/CVE-2025-14010
- type: WEB
  url: https://github.com/ansible-collections/community.general/issues/11000
- type: WEB
  url: https://github.com/ansible-collections/community.general/commit/08e56bbb9b57740a879d3057d84cdb02a162b840
- type: WEB
  url: https://access.redhat.com/security/cve/CVE-2025-14010
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=2418774
- type: PACKAGE
  url: https://github.com/ansible-collections/community.general
- type: WEB
  url: https://github.com/ansible-community/ansible-build-data/blob/12.2.0/12/CHANGELOG-v12.md#security-fixes
- type: PACKAGE
  url: https://pypi.org/project/ansible
- type: ADVISORY
  url: https://github.com/advisories/GHSA-8ggh-xwr9-3373
